### PR TITLE
fix(core): deleted color from tokenCats array because it is not existed in config v3 and v4.

### LINKED ISSUE #3177: ToggleGroup.Item throws error
### Current Behavior

After update to latest Tamagui version `ToggleGroup.Item` stopped working.

Minimal reproduction:
```jsx
        <ToggleGroup type="single">
          <ToggleGroup.Item value="a">
            <ChevronDown />
          </ToggleGroup.Item>
        </ToggleGroup>
```

```
Unhandled Runtime Error
TypeError: Cannot use 'in' operator to search for '' in undefined

Call Stack
getVariantDefinition
```

### Expected Behavior

Should render

### Tamagui Version

```markdown
1.123.3
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

https://codesandbox.io/p/devbox/sad-cookies-8cl78m

### PR DESCRIPTION
**Pull request by zarin-maruf**
Closes #3177

## current behavior 

if you add the following context and variant to any component.
```

export const context = createStyledContext({
  color: '',
})


const StyledView = styled(View, {
  context,

  variants: {
       color: {
        '...color': () => {
          return {}
        },
      },
    }
})

```

it will give you this error 

TypeError: Cannot use 'in' operator to search for '' in undefined. 

This issue happens because config V3 and V4 tokens don't include color, and this snippet code tries to check the color

```
 const { tokensParsed } = conf
    for (const { name, spreadName } of tokenCats) {
      if (spreadName in variant && value in tokensParsed[name]) {
        return variant[spreadName]
      }
    }
```
so `tokensParsed[name]` is undefined  and  `value in tokensParsed[name]` crash the app.

## New behavior 

I removed the color from the tokenCats array, which will no longer check for the color, and it works nicely.

@natew Let me know if there's anything you'd like me to adjust!

### CODE REVIEW

**Comment by natew** [comment]
We still need to check color as its a supported category, what we can do is add a check if it exists in the tokens though first.

**Comment by zarin-maruf** [comment]
> We still need to check color as its a supported category, what we can do is add a check if it exists in the tokens though first.

Thanks, I will address it ASAP

**Comment by zarin-maruf** [comment]
@natew  I’ve addressed your feedback. Let me know if you have any other suggestions. Thanks!

File: code/core/web/src/helpers/propMapper.ts [hunk 1]
```diff
@@ -327,10 +327,14 @@ function getVariantDefinition(variant: any, value: any, conf: TamaguiInternalCon
...
     return exact
   }
-  if (value != null) {
+  if (value != null && (typeof value !== 'string' || value.trim() !== '')) {
     const { tokensParsed } = conf
     for (const { name, spreadName } of tokenCats) {
-      if (spreadName in variant && value in tokensParsed[name]) {
+      if (
+        spreadName in variant &&
+        typeof tokensParsed[name] === 'object' &&
```
Comment (natew) [inline code/core/web/src/helpers/propMapper.ts:335]: no you want `spreadName in variant && name in tokensParsed && ` i think

**Comment by zarin-maruf** [comment]
You're right. I've fixed it now. Let me know if anything else needs adjustment. Thanks!

File: code/core/web/src/helpers/propMapper.ts [hunk 2]
```diff
@@ -327,10 +327,10 @@ function getVariantDefinition(variant: any, value: any, conf: TamaguiInternalCon
   if (exact) {
     return exact
   }
-  if (value != null) {
+  if (value != null && (typeof value !== 'string' || value.trim() !== '')) {
```
Comment (natew) [inline code/core/web/src/helpers/propMapper.ts:330]: dont need this

Comment (zarin-maruf) [reply code/core/web/src/helpers/propMapper.ts]: Value could be an empty string. and that prevents the rest of the code from running. i removed it btw
